<?php

$offersFooterArr = [
["price_1" => "цена на отмостку", "price_1Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/", "price_2" => "выравнивание участка цена", "price_2Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "tag_1" => "услуги по выравниванию участка", "tag_1Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "tag_2" => "отмостка вокруг дома", "tag_2Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["price_1" => "цена на устройство газонов", "price_1Url" => "https://nasha-dachaa.ru/ustrojstvo-posevnogo-gazona/", "price_2" => "выравнивание участка трактором цена", "price_2Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "tag_1" => "услуги по вспашке земли", "tag_1Url" => "https://nasha-dachaa.ru/vspashka-zemli-motoblokom/", "tag_2" => "отмостка дома", "tag_2Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["price_1" => "цена на устройство рулонного газона", "price_1Url" => "https://nasha-dachaa.ru/rulonnyj-gazon/", "price_2" => "выравнивание участка под газон цена", "price_2Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "tag_1" => "услуги по устройству заезда на участок", "tag_1Url" => "https://nasha-dachaa.ru/zaezd-na-uchastok/", "tag_2" => "дренаж участка", "tag_2Url" => "https://nasha-dachaa.ru/drenazh-uchastka/"],
["price_1" => "цена заезда на участок", "price_1Url" => "https://nasha-dachaa.ru/zaezd-na-uchastok/", "price_2" => "выравнивание земельного участка цена", "price_2Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "tag_1" => "услуги по устройству отмостки", "tag_1Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/", "tag_2" => "дренаж вокруг дома", "tag_2Url" => "https://nasha-dachaa.ru/drenazh-uchastka/"],
["price_1" => "цена на выравнивание участка", "price_1Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "price_2" => "выравнивание участка под ключ цена", "price_2Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "tag_1" => "услуги по устройству отмостки вокруг дома", "tag_1Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/", "tag_2" => "заезд на участок", "tag_2Url" => "https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["price_1" => "цена на вспашку земли", "price_1Url" => "https://nasha-dachaa.ru/vspashka-zemli-motoblokom/", "price_2" => "выровнять участок цена", "price_2Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "tag_1" => "услуги по устройству садовых дорожек", "tag_1Url" => "https://nasha-dachaa.ru/sadovye-dorozhki/", "tag_2" => "въезд на участок", "tag_2Url" => "https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["price_1" => "цена на заливку бетона", "price_1Url" => "https://nasha-dachaa.ru/betonnaya-ploshhadka/", "price_2" => "вспашка земли цена", "price_2Url" => "https://nasha-dachaa.ru/vspashka-zemli-motoblokom/", "tag_1" => "услуги по устройству парковки из дорожных плит", "tag_1Url" => "https://nasha-dachaa.ru/parkovka-iz-dorozhnyh-plit/", "tag_2" => "площадка для автомобиля", "tag_2Url" => "https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["price_1" => "цена на расчистку участка", "price_1Url" => "https://nasha-dachaa.ru/raschistka-uchastka-detail/", "price_2" => "вспашка земли трактором цена", "price_2Url" => "https://nasha-dachaa.ru/vspashka-zemli/", "tag_1" => "услуги по устройству площадки из щебня", "tag_1Url" => "https://nasha-dachaa.ru/ploshhadki-iz-shhebnya/", "tag_2" => "площадка под автомобиль", "tag_2Url" => "https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["price_1" => "цена на раскорчевку участка", "price_1Url" => "https://nasha-dachaa.ru/raskorchevka-uchastka/", "price_2" => "вспашка земли в московской области цена", "price_2Url" => "https://nasha-dachaa.ru/vspashka-zemli-motoblokom/", "tag_1" => "услуги по устройству площадки из тротуарной плитки", "tag_1Url" => "https://nasha-dachaa.ru/ploshhadka-iz-bruschatki/", "tag_2" => "парковка для машины на даче", "tag_2Url" => "https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["price_1" => "цена на покос травы", "price_1Url" => "https://nasha-dachaa.ru/pokos-travy/", "price_2" => "вспахать участок мотоблоком цена", "price_2Url" => "https://nasha-dachaa.ru/vspashka-zemli-motoblokom/", "tag_1" => "услуги по устройству бетонной площадки", "tag_1Url" => "https://nasha-dachaa.ru/betonnaya-ploshhadka/", "tag_2" => "парковка из дорожных плит", "tag_2Url" => "https://nasha-dachaa.ru/parkovka-iz-dorozhnyh-plit/"],
["price_1" => "цена на вывоз мусора с участка", "price_1Url" => "https://nasha-dachaa.ru/vyvoz-musora-s-uchastka/", "price_2" => "ландшафтные работы цена", "price_2Url" => "https://nasha-dachaa.ru/landshaftnye-raboty/", "tag_1" => "услуги по устройству площадки из бетона", "tag_1Url" => "https://nasha-dachaa.ru/betonnaya-ploshhadka/", "tag_2" => "садовые дорожки", "tag_2Url" => "https://nasha-dachaa.ru/sadovye-dorozhki/"],
["price_1" => "цена на отсыпку участка", "price_1Url" => "https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/", "price_2" => "ландшафтный дизайн цена", "price_2Url" => "https://nasha-dachaa.ru/landshaftnyj-dizajn/", "tag_1" => "услуги по устройству утепленной отмостки", "tag_1Url" => "https://nasha-dachaa.ru/uteplennaya-otmostka/", "tag_2" => "площадка из щебня", "tag_2Url" => "https://nasha-dachaa.ru/ploshhadki-iz-shhebnya/"],
["price_1" => "стоимость отмостки", "price_1Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/", "price_2" => "ландшафтный дизайн участка цена", "price_2Url" => "https://nasha-dachaa.ru/landshaftnyj-dizajn/", "tag_1" => "услуги по устройству мягкой отмостки", "tag_1Url" => "https://nasha-dachaa.ru/myagkaya-otmostka-vokrug-doma/", "tag_2" => "бетонная площадка", "tag_2Url" => "https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["price_1" => "устройство газонов стоимость", "price_1Url" => "https://nasha-dachaa.ru/ustrojstvo-posevnogo-gazona/", "price_2" => "дизайн дачного участка цена", "price_2Url" => "https://nasha-dachaa.ru/landshaftnyj-dizajn/", "tag_1" => "услуги по устройству бетонной отмостки", "tag_1Url" => "https://nasha-dachaa.ru/betonnaya-otmostka/", "tag_2" => "утепленная отмостка", "tag_2Url" => "https://nasha-dachaa.ru/uteplennaya-otmostka/"],
["price_1" => " стоимость устройства рулонного газона", "price_1Url" => "https://nasha-dachaa.ru/rulonnyj-gazon/", "price_2" => "отмостка дома цена", "price_2Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/", "tag_1" => "услуги по устройству отмостки из тротуарной плитки", "tag_1Url" => "https://nasha-dachaa.ru/otmostka-iz-trotuarnoj-plitki/", "tag_2" => "мягкая отмостка", "tag_2Url" => "https://nasha-dachaa.ru/myagkaya-otmostka-vokrug-doma/"],
["price_1" => "стоимость отсыпки участка", "price_1Url" => "https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/", "price_2" => "мягкая отмостка цена", "price_2Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/", "tag_1" => "услуги по устройству дренажа на участке", "tag_1Url" => "https://nasha-dachaa.ru/drenazh-uchastka/", "tag_2" => "бетонная отмостка", "tag_2Url" => "https://nasha-dachaa.ru/betonnaya-otmostka/"],
["price_1" => "стоимость заезда", "price_1Url" => "https://nasha-dachaa.ru/zaezd-na-uchastok/", "price_2" => "отмостка под ключ цена", "price_2Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/", "tag_1" => "услуги по устройству глубинного дренажа участка", "tag_1Url" => "https://nasha-dachaa.ru/glubinnyj-drenazh/", "tag_2" => "отмостка из тротуарной плитки", "tag_2Url" => "https://nasha-dachaa.ru/otmostka-iz-trotuarnoj-plitki/"],
["price_1" => "стоимость заливки бетона", "price_1Url" => "https://nasha-dachaa.ru/betonnaya-ploshhadka/", "price_2" => "удаление пней цена", "price_2Url" => "https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/", "tag_1" => "услуги по устройству пристенного дренажа участка", "tag_1Url" => "https://nasha-dachaa.ru/pristenyj-drenazh/", "tag_2" => "глубинный дренаж участка", "tag_2Url" => "https://nasha-dachaa.ru/glubinnyj-drenazh/"],
["price_1" => "стоимость выравнивания участка", "price_1Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "price_2" => "удаление пней на участке цена", "price_2Url" => "https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/", "tag_1" => "услуги по устройству кольцевого дренажа участка", "tag_1Url" => "https://nasha-dachaa.ru/kolcevoj-drenazh/", "tag_2" => "пристенный дренаж участка", "tag_2Url" => "https://nasha-dachaa.ru/pristenyj-drenazh/"],
["price_1" => "стоимость выравнивания участка в Московской области", "price_1Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "price_2" => "корчевка цены", "price_2Url" => "https://nasha-dachaa.ru/raskorchevka-uchastka/", "tag_1" => "услуги по устройству ливневки", "tag_1Url" => "https://nasha-dachaa.ru/livnjovka/", "tag_2" => "кольцевой дренаж", "tag_2Url" => "https://nasha-dachaa.ru/kolcevoj-drenazh/"],
["price_1" => "стоимость выравнивания участка под газон", "price_1Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "price_2" => "корчевка пней цена", "price_2Url" => "https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/", "tag_1" => "услуги по  расчистки участка", "tag_1Url" => "https://nasha-dachaa.ru/raschistka-uchastka-detail/", "tag_2" => "ливнёвка", "tag_2Url" => "https://nasha-dachaa.ru/livnjovka/"],
["price_1" => "стоимость вспашки земли", "price_1Url" => "https://nasha-dachaa.ru/vspashka-zemli-motoblokom/", "price_2" => "корчевание цена", "price_2Url" => "https://nasha-dachaa.ru/raskorchevka-uchastka/", "tag_1" => "услуги по уборки участка", "tag_1Url" => "https://nasha-dachaa.ru/uborka-uchastka/", "tag_2" => "расчистка участка", "tag_2Url" => "https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["price_1" => "стоимость вспашки земли трактором", "price_1Url" => "https://nasha-dachaa.ru/vspashka-zemli/", "price_2" => "раскорчевка участка цена", "price_2Url" => "https://nasha-dachaa.ru/raskorchevka-uchastka/", "tag_1" => "услуги по раскорчевки участка", "tag_1Url" => "https://nasha-dachaa.ru/raskorchevka-uchastka/", "tag_2" => "уборка участка", "tag_2Url" => "https://nasha-dachaa.ru/uborka-uchastka/"],
["price_1" => "стоимость ландшафтных работ", "price_1Url" => "https://nasha-dachaa.ru/landshaftnyj-dizajn/", "price_2" => "выкорчевывание участка цена", "price_2Url" => "https://nasha-dachaa.ru/raskorchevka-uchastka/", "tag_1" => "услуги по покосу травы", "tag_1Url" => "https://nasha-dachaa.ru/pokos-travy/", "tag_2" => "покос травы", "tag_2Url" => "https://nasha-dachaa.ru/pokos-travy/"],
["price_1" => "стоимость укладки рулонного газона", "price_1Url" => "https://nasha-dachaa.ru/rulonnyj-gazon/", "price_2" => "выкорчевывание деревьев на участке цена", "price_2Url" => "https://nasha-dachaa.ru/raskorchevka-uchastka/", "tag_1" => "услуги по вывозу мусора с участка", "tag_1Url" => "https://nasha-dachaa.ru/vyvoz-musora-s-uchastka/", "tag_2" => "удаление пней", "tag_2Url" => "https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/"],
["price_1" => "стоимость заливки бетона", "price_1Url" => "https://nasha-dachaa.ru/betonnaya-ploshhadka/", "price_2" => "благоустройство участка цена", "price_2Url" => "https://nasha-dachaa.ru/", "tag_1" => "услуги по сносу ветхих домов", "tag_1Url" => "https://nasha-dachaa.ru/snos-i-demontazh-domov/", "tag_2" => "вывоз мусора с участка", "tag_2Url" => "https://nasha-dachaa.ru/vyvoz-musora-s-uchastka/"],
["price_1" => "стоимость укладки тротуарной плитки", "price_1Url" => "https://nasha-dachaa.ru/ploshhadka-iz-bruschatki/", "price_2" => "благоустройство дачного участка цена", "price_2Url" => "https://nasha-dachaa.ru/", "tag_1" => "услуги по демонтажу ветхих домов", "tag_1Url" => "https://nasha-dachaa.ru/snos-i-demontazh-domov/", "tag_2" => "вырубка кустарника", "tag_2Url" => "https://nasha-dachaa.ru/vyrubka-kustarnika/"],
["price_1" => "стоимость укладки брусчатки", "price_1Url" => "https://nasha-dachaa.ru/ploshhadka-iz-bruschatki/", "price_2" => "благоустройство участка под ключ цена", "price_2Url" => "https://nasha-dachaa.ru/", "tag_1" => "услуги по демонтажу ветхих построек", "tag_1Url" => "https://nasha-dachaa.ru/snos-i-demontazh-domov/", "tag_2" => "измельчение веток в щепу", "tag_2Url" => "https://nasha-dachaa.ru/izmelchenie-vetok-v-shhepu/"],
["price_1" => "стоимость укладки площадки из щебня", "price_1Url" => "https://nasha-dachaa.ru/ploshhadki-iz-shhebnya/", "price_2" => "благоустройство дачного участка под ключ цена", "price_2Url" => "https://nasha-dachaa.ru/", "tag_1" => "услуги по вспашке земли", "tag_1Url" => "https://nasha-dachaa.ru/vspashka-zemli/", "tag_2" => "аренда дробилки", "tag_2Url" => "https://nasha-dachaa.ru/arenda-drobilki/"],
["price_1" => "стоимость укладки бетонной площадки", "price_1Url" => "https://nasha-dachaa.ru/betonnaya-ploshhadka/", "price_2" => "обустройство участка цена", "price_2Url" => "https://nasha-dachaa.ru/", "tag_1" => "услуги по вспашке земли мотоблоком", "tag_1Url" => "https://nasha-dachaa.ru/vspashka-zemli-motoblokom/", "tag_2" => "снос домов", "tag_2Url" => "https://nasha-dachaa.ru/snos-i-demontazh-domov/"],
["price_1" => "стоимость заезда на участок", "price_1Url" => "https://nasha-dachaa.ru/zaezd-na-uchastok/", "price_2" => "устройство газона цена", "price_2Url" => "https://nasha-dachaa.ru/ustrojstvo-posevnogo-gazona/", "tag_1" => "услуги по выравниванию участка", "tag_1Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "tag_2" => "демонтаж домов", "tag_2Url" => "https://nasha-dachaa.ru/snos-i-demontazh-domov/"],
["price_1" => "стоимость бетонного заезда на участок", "price_1Url" => "https://nasha-dachaa.ru/zaezd-betonnyj/", "price_2" => "укладки рулонного газона под ключ цена", "price_2Url" => "https://nasha-dachaa.ru/rulonnyj-gazon/", "tag_1" => "услуги по укладке рулонного газона", "tag_1Url" => "https://nasha-dachaa.ru/rulonnyj-gazon/", "tag_2" => "вспашка земли мотоблоком", "tag_2Url" => "https://nasha-dachaa.ru/vspashka-zemli-motoblokom/"],
["price_1" => "стоимость укладки садовых дорожек", "price_1Url" => "https://nasha-dachaa.ru/sadovye-dorozhki/", "price_2" => "устройство рулонного газона цена", "price_2Url" => "https://nasha-dachaa.ru/rulonnyj-gazon/", "tag_1" => "услуги по устройству посевного газона", "tag_1Url" => "https://nasha-dachaa.ru/ustrojstvo-posevnogo-gazona/", "tag_2" => "вспашка земли", "tag_2Url" => "https://nasha-dachaa.ru/vspashka-zemli/"],
["price_1" => "стоимость парковки из дорожных плит", "price_1Url" => "https://nasha-dachaa.ru/parkovka-iz-dorozhnyh-plit/", "price_2" => "устройство рулонного газона стоимость", "price_2Url" => "https://nasha-dachaa.ru/rulonnyj-gazon/", "tag_1" => "услуги по отсыпке участка", "tag_1Url" => "https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/", "tag_2" => "выравнивание участка", "tag_2Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["price_1" => "стоимость площадки из щебня", "price_1Url" => "https://nasha-dachaa.ru/ploshhadki-iz-shhebnya/", "price_2" => "отсыпка участка цена", "price_2Url" => "https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/", "tag_1" => "услуги по отсыпке земельного участка", "tag_1Url" => "https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/", "tag_2" => "укладка рулонного газона", "tag_2Url" => "https://nasha-dachaa.ru/rulonnyj-gazon/"],
["price_1" => "стоимость отмостки", "price_1Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/", "price_2" => "отсыпка участка грунтом цены", "price_2Url" => "https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/", "tag_1" => "услуги по устройству ландшафтному дизайну", "tag_1Url" => "https://nasha-dachaa.ru/landshaftnyj-dizajn/", "tag_2" => "посевной газон", "tag_2Url" => "https://nasha-dachaa.ru/ustrojstvo-posevnogo-gazona/"],
["price_1" => "стоимость отмостки вокруг дома", "price_1Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/", "price_2" => "отсыпка участка песком цена", "price_2Url" => "https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/", "tag_1" => "услуги по выравниванию участка", "tag_1Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "tag_2" => "рулонный газон", "tag_2Url" => "https://nasha-dachaa.ru/rulonnyj-gazon/"],
["price_1" => "стоимость отмостки дома", "price_1Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/", "price_2" => "выравнивание участка цена", "price_2Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "tag_1" => "услуги по вспашке земли", "tag_1Url" => "https://nasha-dachaa.ru/vspashka-zemli-motoblokom/", "tag_2" => "отсыпка участка", "tag_2Url" => "https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["price_1" => "стоимость бетонной отмостки", "price_1Url" => "https://nasha-dachaa.ru/betonnaya-otmostka/", "price_2" => "выравнивание участка трактором цена", "price_2Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "tag_1" => "услуги по устройству заезда на участок", "tag_1Url" => "https://nasha-dachaa.ru/zaezd-na-uchastok/", "tag_2" => "отсыпка земельного участка", "tag_2Url" => "https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["price_1" => "стоимость утеплённой отмостки", "price_1Url" => "https://nasha-dachaa.ru/uteplennaya-otmostka/", "price_2" => "выравнивание участка под газон цена", "price_2Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "tag_1" => "услуги по устройству отмостки", "tag_1Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/", "tag_2" => "ландшафтный дизайн участка", "tag_2Url" => "https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["price_1" => "стоимость отмостки из тротуарной плитки", "price_1Url" => "https://nasha-dachaa.ru/otmostka-iz-trotuarnoj-plitki/", "price_2" => "выравнивание земельного участка цена", "price_2Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "tag_1" => "услуги по устройству отмостки вокруг дома", "tag_1Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/", "tag_2" => "ландшафтные работы", "tag_2Url" => "https://nasha-dachaa.ru/landshaftnye-raboty/"],
["price_1" => "стоимость дренажа участка", "price_1Url" => "https://nasha-dachaa.ru/drenazh-uchastka/", "price_2" => "выравнивание участка под ключ цена", "price_2Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "tag_1" => "услуги по устройству садовых дорожек", "tag_1Url" => "https://nasha-dachaa.ru/sadovye-dorozhki/", "tag_2" => "отмостка вокруг дома", "tag_2Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["price_1" => "стоимость устройства дренажа участка", "price_1Url" => "https://nasha-dachaa.ru/drenazh-uchastka/", "price_2" => "выровнять участок цена", "price_2Url" => "https://nasha-dachaa.ru/viyravnivanie-uchastka/", "tag_1" => "услуги по устройству парковки из дорожных плит", "tag_1Url" => "https://nasha-dachaa.ru/parkovka-iz-dorozhnyh-plit/", "tag_2" => "отмостка дома", "tag_2Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["price_1" => "стоимость глубинного дренажа участка", "price_1Url" => "https://nasha-dachaa.ru/glubinnyj-drenazh/", "price_2" => "вспашка земли цена", "price_2Url" => "https://nasha-dachaa.ru/vspashka-zemli-motoblokom/", "tag_1" => "услуги по устройству площадки из щебня", "tag_1Url" => "https://nasha-dachaa.ru/ploshhadki-iz-shhebnya/", "tag_2" => "дренаж участка", "tag_2Url" => "https://nasha-dachaa.ru/drenazh-uchastka/"],
["price_1" => "стоимость устройства кольцевого дренажа участка", "price_1Url" => "https://nasha-dachaa.ru/kolcevoj-drenazh/", "price_2" => "вспашка земли трактором цена", "price_2Url" => "https://nasha-dachaa.ru/vspashka-zemli/", "tag_1" => "услуги по устройству площадки из тротуарной плитки", "tag_1Url" => "https://nasha-dachaa.ru/ploshhadka-iz-bruschatki/", "tag_2" => "дренаж вокруг дома", "tag_2Url" => "https://nasha-dachaa.ru/drenazh-uchastka/"],
["price_1" => "стоимость ливнёвки дома", "price_1Url" => "https://nasha-dachaa.ru/livnjovka/", "price_2" => "вспашка земли в московской области цена", "price_2Url" => "https://nasha-dachaa.ru/vspashka-zemli-motoblokom/", "tag_1" => "услуги по устройству бетонной площадки", "tag_1Url" => "https://nasha-dachaa.ru/betonnaya-ploshhadka/", "tag_2" => "заезд на участок", "tag_2Url" => "https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["price_1" => "стоимость поверхностного дренажа участка", "price_1Url" => "https://nasha-dachaa.ru/poverhostnyj-drenazh/", "price_2" => "вспахать участок мотоблоком цена", "price_2Url" => "https://nasha-dachaa.ru/vspashka-zemli-motoblokom/", "tag_1" => "услуги по устройству площадки из бетона", "tag_1Url" => "https://nasha-dachaa.ru/betonnaya-ploshhadka/", "tag_2" => "въезд на участок", "tag_2Url" => "https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["price_1" => "стоимость пристенного дренажа участка", "price_1Url" => "https://nasha-dachaa.ru/pristenyj-drenazh/", "price_2" => "ландшафтные работы цена", "price_2Url" => "https://nasha-dachaa.ru/landshaftnye-raboty/", "tag_1" => "услуги по устройству утепленной отмостки", "tag_1Url" => "https://nasha-dachaa.ru/uteplennaya-otmostka/", "tag_2" => "площадка для автомобиля", "tag_2Url" => "https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["price_1" => "стоимость расчистки участка", "price_1Url" => "https://nasha-dachaa.ru/raschistka-uchastka-detail/", "price_2" => "ландшафтный дизайн цена", "price_2Url" => "https://nasha-dachaa.ru/landshaftnyj-dizajn/", "tag_1" => "услуги по устройству мягкой отмостки", "tag_1Url" => "https://nasha-dachaa.ru/myagkaya-otmostka-vokrug-doma/", "tag_2" => "площадка под автомобиль", "tag_2Url" => "https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["price_1" => "стоимость раскорчевки участка", "price_1Url" => "https://nasha-dachaa.ru/raskorchevka-uchastka/", "price_2" => "ландшафтный дизайн участка цена", "price_2Url" => "https://nasha-dachaa.ru/landshaftnyj-dizajn/", "tag_1" => "услуги по устройству бетонной отмостки", "tag_1Url" => "https://nasha-dachaa.ru/betonnaya-otmostka/", "tag_2" => "парковка для машины на даче", "tag_2Url" => "https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["price_1" => "стоимость покоса травы", "price_1Url" => "https://nasha-dachaa.ru/pokos-travy/", "price_2" => "дизайн дачного участка цена", "price_2Url" => "https://nasha-dachaa.ru/landshaftnyj-dizajn/", "tag_1" => "услуги по устройству отмостки из тротуарной плитки", "tag_1Url" => "https://nasha-dachaa.ru/otmostka-iz-trotuarnoj-plitki/", "tag_2" => "парковка из дорожных плит", "tag_2Url" => "https://nasha-dachaa.ru/parkovka-iz-dorozhnyh-plit/"],
["price_1" => "стоимость удаления пней", "price_1Url" => "https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/", "price_2" => "отмостка дома цена", "price_2Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/", "tag_1" => "услуги по устройству дренажа на участке", "tag_1Url" => "https://nasha-dachaa.ru/drenazh-uchastka/", "tag_2" => "садовые дорожки", "tag_2Url" => "https://nasha-dachaa.ru/sadovye-dorozhki/"],
["price_1" => "стоимость вывоза мусора с участка", "price_1Url" => "https://nasha-dachaa.ru/vyvoz-musora-s-uchastka/", "price_2" => "мягкая отмостка цена", "price_2Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/", "tag_1" => "услуги по устройству глубинного дренажа участка", "tag_1Url" => "https://nasha-dachaa.ru/glubinnyj-drenazh/", "tag_2" => "площадка из щебня", "tag_2Url" => "https://nasha-dachaa.ru/ploshhadki-iz-shhebnya/"],
["price_1" => "стоимость вырубки кустарника", "price_1Url" => "https://nasha-dachaa.ru/vyrubka-kustarnika/", "price_2" => "отмостка под ключ цена", "price_2Url" => "https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/", "tag_1" => "услуги по устройству пристенного дренажа участка", "tag_1Url" => "https://nasha-dachaa.ru/pristenyj-drenazh/", "tag_2" => "бетонная площадка", "tag_2Url" => "https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["price_1" => "стоимость уборки участка", "price_1Url" => "https://nasha-dachaa.ru/uborka-uchastka/", "price_2" => "удаление пней цена", "price_2Url" => "https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/", "tag_1" => "услуги по устройству кольцевого дренажа участка", "tag_1Url" => "https://nasha-dachaa.ru/kolcevoj-drenazh/", "tag_2" => "утепленная отмостка", "tag_2Url" => "https://nasha-dachaa.ru/uteplennaya-otmostka/"],
["price_1" => "стоимость измельчения веток в щепу", "price_1Url" => "https://nasha-dachaa.ru/izmelchenie-vetok-v-shhepu/", "price_2" => "удаление пней на участке цена", "price_2Url" => "https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/", "tag_1" => "услуги по устройству ливневки", "tag_1Url" => "https://nasha-dachaa.ru/livnjovka/", "tag_2" => "мягкая отмостка", "tag_2Url" => "https://nasha-dachaa.ru/myagkaya-otmostka-vokrug-doma/"],
["price_1" => "стоимость аренды дробилки", "price_1Url" => "https://nasha-dachaa.ru/arenda-drobilki/", "price_2" => "корчевка цены", "price_2Url" => "https://nasha-dachaa.ru/raskorchevka-uchastka/", "tag_1" => "услуги по  расчистки участка", "tag_1Url" => "https://nasha-dachaa.ru/raschistka-uchastka-detail/", "tag_2" => "бетонная отмостка", "tag_2Url" => "https://nasha-dachaa.ru/betonnaya-otmostka/"],
["price_1" => "стоимость сноса домов", "price_1Url" => "https://nasha-dachaa.ru/snos-i-demontazh-domov/", "price_2" => "корчевка пней цена", "price_2Url" => "https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/", "tag_1" => "услуги по уборки участка", "tag_1Url" => "https://nasha-dachaa.ru/uborka-uchastka/", "tag_2" => "отмостка из тротуарной плитки", "tag_2Url" => "https://nasha-dachaa.ru/otmostka-iz-trotuarnoj-plitki/"],
["price_1" => "стоимость демонтажа домов", "price_1Url" => "https://nasha-dachaa.ru/snos-i-demontazh-domov/", "price_2" => "корчевание цена", "price_2Url" => "https://nasha-dachaa.ru/raskorchevka-uchastka/", "tag_1" => "услуги по раскорчевки участка", "tag_1Url" => "https://nasha-dachaa.ru/raskorchevka-uchastka/", "tag_2" => "глубинный дренаж участка", "tag_2Url" => "https://nasha-dachaa.ru/glubinnyj-drenazh/"],
["price_1" => "стоимость ландшафтного дизайна", "price_1Url" => "https://nasha-dachaa.ru/landshaftnyj-dizajn/", "price_2" => "раскорчевка участка цена", "price_2Url" => "https://nasha-dachaa.ru/raskorchevka-uchastka/", "tag_1" => "услуги по покосу травы", "tag_1Url" => "https://nasha-dachaa.ru/pokos-travy/", "tag_2" => "пристенный дренаж участка", "tag_2Url" => "https://nasha-dachaa.ru/pristenyj-drenazh/"],
["price_1" => "стоимость отсыпки участка", "price_1Url" => "https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/", "price_2" => "выкорчевывание участка цена", "price_2Url" => "https://nasha-dachaa.ru/raskorchevka-uchastka/", "tag_1" => "услуги по вывозу мусора с участка", "tag_1Url" => "https://nasha-dachaa.ru/vyvoz-musora-s-uchastka/", "tag_2" => "кольцевой дренаж", "tag_2Url" => "https://nasha-dachaa.ru/kolcevoj-drenazh/"],
["price_1" => "стоимость отсыпки земельного участка", "price_1Url" => "https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/", "price_2" => "выкорчевывание деревьев на участке цена", "price_2Url" => "https://nasha-dachaa.ru/raskorchevka-uchastka/", "tag_1" => "услуги по сносу ветхих домов", "tag_1Url" => "https://nasha-dachaa.ru/snos-i-demontazh-domov/", "tag_2" => "ливнёвка", "tag_2Url" => "https://nasha-dachaa.ru/livnjovka/"]

];

global $wpdb;

$postId = get_the_ID();

// Эта функция размешивает элементы ассоциативного массива
function shuffle_offers_arr($my_array)
{
$keys = array_keys($my_array);

shuffle($keys);

foreach($keys as $key) {
    $new[$key] = $my_array[$key];
}

$my_array = $new;

return $my_array;
}

function displayFooterOffers($arr){
    $postId = get_the_ID();
    $currentUrl = home_url( add_query_arg( array(), $wp->request ) );
    
    $shf = shuffle_offers_arr($arr);
    $finalArr = array_slice($shf,10);
    //print_r($finalArr[0]);
    
    for($i=0; $i < 7; $i++) {
        if($finalArr[$i]["price_1Url"] !== $currentUrl && $finalArr[$i]["price_2Url"] !== $currentUrl && $finalArr[$i]["tag_1Url"] !== $currentUrl && $finalArr[$i]["tag_2Url"] !== $currentUrl){
            $GLOBALS['wpdb']->insert('wp_myseo_offers', array("post_id" => $postId, "price_one" => $finalArr[$i]["price_1"], "price_one_url" => $finalArr[$i]["price_1Url"], "price_two" => $finalArr[$i]["price_2"], "price_two_url" => $finalArr[$i]["price_2Url"], "tag_one" => $finalArr[$i]["tag_1"], "tag_one_url" => $finalArr[$i]["tag_1Url"], "tag_two" => $finalArr[$i]["tag_2"], "tag_two_url" => $finalArr[$i]["tag_2Url"]));
        }
    }
    
   
    

}
 
 
//displayFooterOffers($offersFooterArr);

$seoOffersQ = $wpdb->get_results( "SELECT * FROM wp_myseo_offers WHERE post_id='$postId'");

if(!empty($seoOffersQ)) {
    
   echo '<ul class=\'offers-footer\'>';
   //print_r($seoOffersQ);
   
       
       echo '<li>У нас на сайте можно заказать <a href="'.$seoOffersQ[0]->tag_one_url.'" title="'.$seoOffersQ[0]->tag_one.'">'.$seoOffersQ[0]->tag_one.'</a> Московская область!</li>   
<li>Наши опытные мастера выполнят услугу <a href="'.$seoOffersQ[1]->tag_two_url.'" title="'.$seoOffersQ[1]->tag_two.'">'.$seoOffersQ[1]->tag_two.'</a> качественно и в короткие сроки, а '.$seoOffersQ[4]->price_one.' приятно удивит!</li>   
<li><span id="capitalize-word">'.$seoOffersQ[3]->tag_one.'</span>, <a href="'.$seoOffersQ[5]->price_two_url.'" title="'.$seoOffersQ[5]->price_two.'">'.$seoOffersQ[5]->price_two.'</a> ниже конкурентов!</li>   
<li>У нас самая выгодная <a href="'.$seoOffersQ[6]->price_one_url.'" title="'.$seoOffersQ[6]->price_one.'">'.$seoOffersQ[6]->price_one.'</a>, а также на '.$seoOffersQ[5]->tag_one.'!</li>';
   
   
   echo '</ul>';
    
    
    
} else {
   displayFooterOffers($offersFooterArr); 
}

?>

