<?php $sq = [
    ["anchor"=>"заезд на участок", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"заезд на участок через канаву", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"заезд участок ключ", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"заезд на участок под ключ", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"заезд на участок под ключ цена", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"заезд на участок цена", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"заезд цена", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"заезд во двор", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"заезд на канаву цена", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"заезд через канаву цена", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"заезд на участок через канаву цена", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"заезд под ключ", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"заезд для машины", "url"=>"https://nasha-dachaa.ru/zaezd-standart/"],
["anchor"=>"сделать заезд машины сделать", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"заезд площадку", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"труба бетонная на заезд купить", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"труба под заезд", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"бетонный заезд", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"бетонный заезд на участок", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"бетонная труба на заезд", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"труба на заезд", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"труба в канаву на заезд", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"труба для заезда на участок", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"труба на заезд в канаву купить", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"сделать въезд", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"строительство въездов", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"сделать въезд на участок", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"сделать въезд через канаву", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"сделать заезд на участок", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"въезд во двор", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"железобетонная труба", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"купить трубу железобетонную", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"труба жб", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"въезд на участок", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"план въезда на участок", "url"=>"https://nasha-dachaa.ru/articles/kak-sdelat-zaezd-na-uchastok-etapy-i-osobennosti-rabot/"],
["anchor"=>"канава въезд на участок", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"въезд на участок через канаву", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"труба для въезда на участок", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"въезд на участок купить", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"въезд на дачный участок", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"въезд на участок снт", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"ширина въезда на участок", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"въезд на строительную площадку", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"въезд в гараж площадка", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"площадка на въезде на участок", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"бетонный въезд на участок", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"въезд под ключ", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"въезд на участок под ключ", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"въезд ключ участок", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"въезд на участок цена", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"въезды садовые участки", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"выполнить въезд на участок", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"въезд на участок через канаву цена", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"въезд на участок через трубу", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"сделать дренаж на участке", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"сделать дренаж", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж грунтовых вод", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж участок", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж под ключ", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж цена", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж участка цена", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж под ключ цена", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж участка под ключ цена", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж дома цена", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж участка под ключ московская область", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж участка под ключ цена московская область", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"поверхностный дренаж участка", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"поверхностный дренаж глинистого участка", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"глубинный дренаж участка", "url"=>"https://nasha-dachaa.ru/glubinnyj-drenazh/"],
["anchor"=>"глубинный дренаж участка на глинистых почвах", "url"=>"https://nasha-dachaa.ru/glubinnyj-drenazh/"],
["anchor"=>"дренаж участка почвы", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж глинистого участка", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж дома", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж вокруг дома", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"сделать дренаж дома", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж частного дома", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж фундамента дома", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж участка дома", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж вокруг дома под ключ", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"дренаж вокруг дома  ключ", "url"=>"https://nasha-dachaa.ru/drenazh-uchastka/"],
["anchor"=>"расчистка участка", "url"=>"https://nasha-dachaa.ru/uborka-i-raschistka-uchastka/"],
["anchor"=>"расчистка участка от деревьев", "url"=>"https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["anchor"=>"расчистка участка цена", "url"=>"https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["anchor"=>"расчистка участка от кустарников", "url"=>"https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["anchor"=>"расчистка участка от деревьев и кустарников", "url"=>"https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["anchor"=>"расчистка участка от кустарников цена", "url"=>"https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["anchor"=>"расчистка участка от деревьев цена", "url"=>"https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["anchor"=>"расчистка участка от деревьев и кустарников цена", "url"=>"https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["anchor"=>"расчистка участка область", "url"=>"https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["anchor"=>"расчистка участка московская область", "url"=>"https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["anchor"=>"расчистка участка цена московская область", "url"=>"https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["anchor"=>"расчистка дачного участка", "url"=>"https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["anchor"=>"расчистка участка сотка", "url"=>"https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["anchor"=>"расчистка участка цена за сотку", "url"=>"https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["anchor"=>"расчистка деревьев", "url"=>"https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["anchor"=>"расчистка деревьев кустарников", "url"=>"https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["anchor"=>"расчистка от кустарников", "url"=>"https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["anchor"=>"площадка машина", "url"=>"https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["anchor"=>"парковка дача", "url"=>"https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["anchor"=>"автомобиле заезд", "url"=>"https://nasha-dachaa.ru/zaezd-standart/"],
["anchor"=>"площадка под автомобиль", "url"=>"https://nasha-dachaa.ru/ploshhadki-iz-shhebnya/"],
["anchor"=>"площадка под машину", "url"=>"https://nasha-dachaa.ru/ploshhadki-iz-shhebnya/"],
["anchor"=>"площадка под автомобиль на даче", "url"=>"https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["anchor"=>"площадка для въезда", "url"=>"https://nasha-dachaa.ru/zaezd-na-uchastok/"],
["anchor"=>"бетонные площадки под авто", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"Площадка под автомобиль", "url"=>"https://nasha-dachaa.ru/ploshhadki-iz-shhebnya/"],
["anchor"=>"Площадка под автомобиль на даче", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"Бетонная площадка под автомобиль", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"Бетонная площадка", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"Площадка под авто", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"Площадка под машину", "url"=>"https://nasha-dachaa.ru/ploshhadki-iz-shhebnya/"],
["anchor"=>"Площадка для автомобиля", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"площадка во дворе", "url"=>"https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["anchor"=>"площадка для дачи", "url"=>"https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["anchor"=>"бетонная площадка", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"бетонная площадка цена", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"бетонные работы", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"бетонные работы москва", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"бетон заливка", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"заливка бетона цена", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"заливка пола бетоном", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"заливка бетона стоимость", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"заливка бетоном площадки", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"бетонирование площадки", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"парковка на даче", "url"=>"https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["anchor"=>"площадка под бетон", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"площадка из бетона", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"залить площадку бетоном", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"бетонная парковка", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"площадка из щебня", "url"=>"https://nasha-dachaa.ru/ploshhadki-iz-shhebnya/"],
["anchor"=>"площадка под щебень", "url"=>"https://nasha-dachaa.ru/ploshhadki-iz-shhebnya/"],
["anchor"=>"площадка из щебня на даче", "url"=>"https://nasha-dachaa.ru/ploshhadki-iz-shhebnya/"],
["anchor"=>"парковка из щебня", "url"=>"https://nasha-dachaa.ru/ploshhadki-iz-shhebnya/"],
["anchor"=>"парковка на даче из щебня", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"бетонное основание", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"укладка брусчатки на бетонное основание", "url"=>"https://nasha-dachaa.ru/ploshhadka-iz-bruschatki/"],
["anchor"=>"плитка на бетонное основание", "url"=>"https://nasha-dachaa.ru/ploshhadka-iz-bruschatki/"],
["anchor"=>"основание парковки", "url"=>"https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["anchor"=>"тротуарная плитка на бетонное основание", "url"=>"https://nasha-dachaa.ru/ploshhadka-iz-bruschatki/"],
["anchor"=>"укладка тротуарной на бетонное основание", "url"=>"https://nasha-dachaa.ru/ploshhadka-iz-bruschatki/"],
["anchor"=>"площадка на даче под ключ", "url"=>"https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["anchor"=>"площадки под ключ", "url"=>"https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["anchor"=>"площадки под автомобиль под ключ", "url"=>"https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["anchor"=>"парковка под ключ", "url"=>"https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["anchor"=>"залить двор бетоном", "url"=>"https://nasha-dachaa.ru/betonnaya-ploshhadka/"],
["anchor"=>"площадка участка", "url"=>"https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["anchor"=>"площадка перед участком", "url"=>"https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["anchor"=>"залить площадку", "url"=>"https://nasha-dachaa.ru/ploshhadka-dlya-avtomobilya/"],
["anchor"=>"выравнивание участка", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка трактором", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка стоимость", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка область", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка московская область", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка стоимость работ", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание земельного участка", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка газон", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка под газон", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка стоимость московская область", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка стоимость работ московская", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивания участка сотку", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка стоимость работ московская область", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"грунт для выравнивания участка", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка цена за сотку", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"заказать выравнивание участка", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"заказать трактор для выравнивания участка", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"сколько стоит выравнивание участка", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание земли на участке", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание дачного участка", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка ключ", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка под ключ", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка газон цены", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"земля для выравнивания участка купить", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка газон стоимость", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка в подмосковье", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка под газон стоимость", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка цена за сотку московская", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание заболоченного участка", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка цена за сотку московская область", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка минитрактором", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка уровню", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка газон работ", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка под газон стоимость работ", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"работы по выравниванию участка", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"расчистка и выравнивание участка", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"выравнивание участка строительство", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"вспашка земли", "url"=>"https://nasha-dachaa.ru/vspashka-zemli/"],
["anchor"=>"вспашка земли трактором", "url"=>"https://nasha-dachaa.ru/viyravnivanie-uchastka/"],
["anchor"=>"вспашка земли мотоблоком", "url"=>"https://nasha-dachaa.ru/vspashka-zemli-motoblokom/"],
["anchor"=>"вспашка земли сотка", "url"=>"https://nasha-dachaa.ru/vspashka-zemli-motoblokom/"],
["anchor"=>"вспашка земли цена за сотку", "url"=>"https://nasha-dachaa.ru/vspashka-zemli-motoblokom/"],
["anchor"=>"вспашка земли трактором цена", "url"=>"https://nasha-dachaa.ru/vspashka-zemli/"],
["anchor"=>"вспашка земли области", "url"=>"https://nasha-dachaa.ru/vspashka-zemli-motoblokom/"],
["anchor"=>"вспашка земли трактором цена за сотку", "url"=>"https://nasha-dachaa.ru/vspashka-zemli/"],
["anchor"=>"вспашка земли минитрактором", "url"=>"https://nasha-dachaa.ru/vspashka-zemli/"],
["anchor"=>"вспашка земли московская область", "url"=>"https://nasha-dachaa.ru/vspashka-zemli/"],
["anchor"=>"вспашка земли стоимость", "url"=>"https://nasha-dachaa.ru/vspashka-zemli-motoblokom/"],
["anchor"=>"вспашка земли мотоблоком цена за сотку", "url"=>"https://nasha-dachaa.ru/vspashka-zemli-motoblokom/"],
["anchor"=>"вспашка сельскохозяйственных земель", "url"=>"https://nasha-dachaa.ru/vspashka-zemli/"],
["anchor"=>"вспашка земли трактором стоимость", "url"=>"https://nasha-dachaa.ru/vspashka-zemli/"],
["anchor"=>"вспашка земли стоимость за сотку", "url"=>"https://nasha-dachaa.ru/vspashka-zemli-motoblokom/"],
["anchor"=>"вспашка земли цена за гектар", "url"=>"https://nasha-dachaa.ru/vspashka-zemli/"],
["anchor"=>"вспашка земли на участке", "url"=>"https://nasha-dachaa.ru/vspashka-zemli-motoblokom/"],
["anchor"=>"культивация земли", "url"=>"https://nasha-dachaa.ru/vspashka-zemli-motoblokom/"],
["anchor"=>"аренда трактора для вспашки земли", "url"=>"https://nasha-dachaa.ru/vspashka-zemli-motoblokom/"],
["anchor"=>"культиватор вспашка", "url"=>"https://nasha-dachaa.ru/vspashka-zemli-motoblokom/"],
["anchor"=>"вспашка земли культиватором", "url"=>"https://nasha-dachaa.ru/vspashka-zemli-motoblokom/"],
["anchor"=>"ландшафтные работы", "url"=>"https://nasha-dachaa.ru/landshaftnye-raboty/"],
["anchor"=>"ландшафтные работы москва", "url"=>"https://nasha-dachaa.ru/landshaftnye-raboty/"],
["anchor"=>"ландшафтные работы на участке", "url"=>"https://nasha-dachaa.ru/landshaftnye-raboty/"],
["anchor"=>"стоимость ландшафтных работ", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн участка", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"дачный ландшафтный дизайн", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн дома", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн москва", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн сада", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн садового участка", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн участка соток", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн заказать", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"загородный ландшафтный дизайн", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн загородного дома", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн под ключ", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн участка заказать", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн дачного участка", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн участка фото", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн маленького участка", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"создать ландшафтный дизайн участка", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн узкого участка", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн дачного участка 10", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн прямоугольного участка", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн участок 12", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафт сада", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"дизайн дачного участка", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"дизайн дачного участка соток", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"дизайн ландшафта дачного участка", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн дачного участка под ключ", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"дизайн дачного участка под ключ", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"дизайн дачного участка 15", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"дизайн дачного участка 15 соток", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"ландшафтный дизайн дачного участка цена", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"проект ландшафтного дизайна участка", "url"=>"https://nasha-dachaa.ru/landshaftnyj-dizajn/"],
["anchor"=>"отмостка вокруг дома", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка цена", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка вокруг дома цена", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка фундамента", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"бетонная отмостка", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"правильная отмостка", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"сделать отмостку вокруг", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка здания", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"под отмостку", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка дома своими руками", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка вокруг дома своими руками", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"как сделать отмостку вокруг дома", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка из плитки", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"тротуарная отмостка", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка дома работ", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка тротуарной плиткой", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка плитки домом", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"утепленная отмостка", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка вокруг дома работы", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка дома как правильно", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка дома", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка вокруг", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"мягкая отмостка", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка цоколя", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка под домом", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка из щебня", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка дома щебень", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка из щебня вокруг дома", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"мягкая отмостка дома", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"мягкая отмостка вокруг дома", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка под ключ", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка дома под ключ", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"отмостка вокруг дома под ключ", "url"=>"https://nasha-dachaa.ru/otmostka-vokrug-doma-pod-kliuch/"],
["anchor"=>"удаление пней", "url"=>"https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/"],
["anchor"=>"селитра для удаления пней", "url"=>"https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/"],
["anchor"=>"удаление пней корчеванием", "url"=>"https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/"],
["anchor"=>"удаление пней на участке", "url"=>"https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/"],
["anchor"=>"удаление пней деревьев", "url"=>"https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/"],
["anchor"=>"удаление пней москва", "url"=>"https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/"],
["anchor"=>"удаление пней пнедробилкой", "url"=>"https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/"],
["anchor"=>"удаление пней цена московская", "url"=>"https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/"],
["anchor"=>"удаление пней цена московская область", "url"=>"https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/"],
["anchor"=>"корчевка пней", "url"=>"https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/"],
["anchor"=>"корчевка деревьев", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"корчевка корень", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"корчевка пней деревьев", "url"=>"https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/"],
["anchor"=>"корчевка участка", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"корчевка кустарника", "url"=>"https://nasha-dachaa.ru/raschistka-uchastka-detail/"],
["anchor"=>"корчевание", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"корчевание пней", "url"=>"https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/"],
["anchor"=>"корчевание пней на участке", "url"=>"https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/"],
["anchor"=>"убрать пень корчевания", "url"=>"https://nasha-dachaa.ru/korchevka-i-udalenie-pnej/"],
["anchor"=>"корчевание участка", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"корчевание деревьев на участке", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"корчевание участка цена", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"корчевание деревьев", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"цена корчевания деревьев", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"раскорчевка участка", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"выкорчевывание участка", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"выкорчевывание деревьев", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"выкорчевывание деревьев на участке", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"выкорчевывание деревьев цена", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"выкорчевывание пней на участке", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"выкорчевывание деревьев область", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"выкорчевывание деревьев участке область", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"избавится пня выкорчевывания", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"выкорчевывание деревьев цена московская область", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"выкорчевывание деревьев на участке цена московская", "url"=>"https://nasha-dachaa.ru/raskorchevka-uchastka/"],
["anchor"=>"благоустройство придомовой территории", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство участка", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство дачного участка", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство земельного участка", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство территории участка", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство участка дома", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"участок сотки благоустройство", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство участков ключ", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство участка под ключ", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство территории земельного участка", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство и озеленение участка", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройству участка строительство", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"проект благоустройства участка", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство частного участка", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство участка частного дома", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"участок 6 соток благоустройство", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство дачного участка под ключ", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"работы по благоустройству участка", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство дачного участка 6", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство дачного участка 6 соток", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство участка ключ ценами", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство загородного участка", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство участка москва", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство садового участка", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство участка недорого", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство участка московская область", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"земельный участок под благоустройство", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство дачного участка недорого", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"начальник участка благоустройства", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"объекты благоустройства земельного участка", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство территории", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"озеленение и благоустройство территории", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство территории область", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"комплексное благоустройство территории", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство территории московская область", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"благоустройство домов придомовой территории", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"обустройство участка", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"обустройство дачного участка", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"обустройство участка сотки", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"строительство обустройство участков", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"обустройство дома и участка", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"обустройство земельного участка", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"загородный участок обустройство", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"обустройство участка под ключ", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"обустройство садового участка", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"обустройство территории", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"обустройство территории дома", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"обустройство территории вокруг дачного домика", "url"=>"https://nasha-dachaa.ru/"],
["anchor"=>"устройство газона", "url"=>"https://nasha-dachaa.ru/ustrojstvo-posevnogo-gazona/"],
["anchor"=>"устройство посевного газона", "url"=>"https://nasha-dachaa.ru/ustrojstvo-posevnogo-gazona/"],
["anchor"=>"устройство газона под ключ", "url"=>"https://nasha-dachaa.ru/ustrojstvo-posevnogo-gazona/"],
["anchor"=>"устройство газонов ключ", "url"=>"https://nasha-dachaa.ru/ustrojstvo-posevnogo-gazona/"],
["anchor"=>"устройство газона расценка", "url"=>"https://nasha-dachaa.ru/ustrojstvo-posevnogo-gazona/"],
["anchor"=>"устройство газона москва", "url"=>"https://nasha-dachaa.ru/ustrojstvo-posevnogo-gazona/"],
["anchor"=>"укладка рулонного газона", "url"=>"https://nasha-dachaa.ru/rulonnyj-gazon/"],
["anchor"=>"цена укладки рулонного газона", "url"=>"https://nasha-dachaa.ru/rulonnyj-gazon/"],
["anchor"=>"укладка рулонного газона москва", "url"=>"https://nasha-dachaa.ru/rulonnyj-gazon/"],
["anchor"=>"стоимость укладки рулонного газона", "url"=>"https://nasha-dachaa.ru/rulonnyj-gazon/"],
["anchor"=>"укладка рулонного газона под ключ", "url"=>"https://nasha-dachaa.ru/rulonnyj-gazon/"],
["anchor"=>"укладка рулонных газонов ключ", "url"=>"https://nasha-dachaa.ru/rulonnyj-gazon/"],
["anchor"=>"укладка рулонного газона цена за м2", "url"=>"https://nasha-dachaa.ru/rulonnyj-gazon/"],
["anchor"=>"технология укладки рулонного газона", "url"=>"https://nasha-dachaa.ru/rulonnyj-gazon/"],
["anchor"=>"рулонный газон после укладки", "url"=>"https://nasha-dachaa.ru/rulonnyj-gazon/"],
["anchor"=>"укладка рулонного газона своими руками", "url"=>"https://nasha-dachaa.ru/rulonnyj-gazon/"],
["anchor"=>"укладка рулонного газона цена москва", "url"=>"https://nasha-dachaa.ru/rulonnyj-gazon/"],
["anchor"=>"купить рулонный газон с укладкой", "url"=>"https://nasha-dachaa.ru/rulonnyj-gazon/"],
["anchor"=>"устройство рулонного газона", "url"=>"https://nasha-dachaa.ru/rulonnyj-gazon/"],
["anchor"=>"отсыпка участка", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["anchor"=>"отсыпка участка грунтом", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["anchor"=>"отсыпка участка песком", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["anchor"=>"отсыпка участка московская область", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["anchor"=>"земля для отсыпки участка", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["anchor"=>"отсыпка земельного участка", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["anchor"=>"отсыпка участка под ключ", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["anchor"=>"поднять участок", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["anchor"=>"отсыпка участка под строительство дома", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["anchor"=>"отсыпка участок", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["anchor"=>"отсыпка грунта", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["anchor"=>"поднятый участок земли", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["anchor"=>"поднять уровень участка", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["anchor"=>"поднять уровень земли на участке", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["anchor"=>"засыпка участка", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["anchor"=>"земляная насыпь", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["anchor"=>"насыпь земляного полотна", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"],
["anchor"=>"низкий участок", "url"=>"https://nasha-dachaa.ru/otsypka-zemelnogo-uchastka/"]

];

global $wpdb;
$postId = get_the_ID();

// Эта функция размешивает элементы ассоциативного массива
function shuffle_assoc($my_array)
{
$keys = array_keys($my_array);

shuffle($keys);

foreach($keys as $key) {
    $new[$key] = $my_array[$key];
}

$my_array = $new;

return $my_array;
}

function displaySearchQueries($arr){
    global $wp;
    $output = '';
    $postId = get_the_ID();
    
   $currentUrl = home_url( add_query_arg( array(), $wp->request ) );
    
     $shf = shuffle_assoc($arr);
     $finalArr = array_slice($shf,2);
        
    for($i=0; $i < 10; $i++) {
        if($finalArr[$i]["url"] !== $currentUrl){
            
            
            
            $GLOBALS['wpdb']->insert('wp_myseo_links', array("post_id" => $postId, "anchor" => $finalArr[$i]["anchor"], "url" => $finalArr[$i]["url"]));

            
        }
     
  }
  
  
  
 
}





?>


<?php 




$se0LinkQ = $wpdb->get_results( "SELECT * FROM wp_myseo_links WHERE post_id='$postId'");

if(!empty($se0LinkQ)) { 

  
 echo '<ul class=\'zaprosi-ul\'>';
 foreach ($se0LinkQ as $q) {
     echo '<li><a href="'.$q->url.'" title="'.$q->anchor.'">'.$q->anchor.'</a></li>';
 }
 echo '</ul>';

} else {
    displaySearchQueries($sq);
}

 ?>








